'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''muffinImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents muffinImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''placeYourOrderHereLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents placeYourOrderHereLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''muffinsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents muffinsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''muffinsTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents muffinsTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''doughnutLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents doughnutLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''doughnutsTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents doughnutsTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''totalOrderItemsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalOrderItemsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''totalItemsOrdered1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalItemsOrdered1Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''totalItemsOrdered2Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalItemsOrdered2Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''totalSalesAmountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalSalesAmountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''totalPriceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalPriceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''submitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitButton As Global.System.Web.UI.WebControls.Button
End Class
